version: "3"
services:
  ngrok:
    build:
      context: ./ngrok
    environment:
      - NGROK_AUTH_TOKEN=$NGROK_AUTH_TOKEN
    volumes:
      - "./ngrok/ngrok.yml:/root/ngrok.yml"
      - "./ngrok/entrypoint.sh:/entrypoint.sh"
    ports:
      - "4040:4040"
    entrypoint:
      - "/entrypoint.sh"
  nginx:
    image: nginx:mainline-alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"
    depends_on:
      - frontend
    restart: always
  frontend:
    build: ./frontend
    volumes:
      - "./frontend/src:/usr/src/app/src"
      - "./frontend/public:/usr/src/app/public"
      - "./frontend/package-lock.json:/usr/src/app/package-lock.json"
      - "./frontend/package.json:/usr/src/app/package.json"
    expose:
      - "3000"